apiVersion: apps/v1
kind: Deployment
metadata:
  name: publishers-service-deployment
  labels:
    app: publishers-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publishers-service
  template:
    metadata:
      labels:
        app: publishers-service
    spec:
      containers:
      - name: publishers-svc
        image: book-publishers:v1
        ports:
        - containerPort: 80